INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (1, 'Conroy, Erdman and Metz', 12);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (2, 'Mayer Inc', 17);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (3, 'Kreiger-Barrows', 6);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (4, 'Blick-Streich', 14);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (5, 'Vandervort, Wehner and Ullrich', 5);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (6, 'Wilkinson-Dickens', 8);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (7, 'Olson, Davis and Shields', 9);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (8, 'Dicki, Stroman and Wiegand', 25);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (9, 'Cole-Hermann', 4);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (10, 'Wunsch-Hamill', 18);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (11, 'DuBuque Inc', 22);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (12, 'Barrows, Mante and Schmeler', 19);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (13, 'Gislason, Legros and Huels', 1);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (14, 'MacGyver Inc', 21);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (15, 'Fisher, Casper and Reinger', 21);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (16, 'Rohan LLC', 25);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (17, 'Stracke, Koch and Schmidt', 25);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (18, 'Ziemann LLC', 6);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (19, 'Strosin-Grady', 16);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (20, 'Ward, Klocko and Beier', 17);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (21, 'Dickinson, Fritsch and Pacocha', 18);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (22, 'Eichmann-Rutherford', 17);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (23, 'Steuber Group', 13);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (24, 'Baumbach, Kunze and Barton', 5);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (25, 'Powlowski Inc', 14);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (26, 'O''Hara-Carroll', 6);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (27, 'Jacobs-Parker', 14);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (28, 'Kilback and Sons', 20);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (29, 'Kunde, Reynolds and Hyatt', 9);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (30, 'Gleason-Gutmann', 15);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (31, 'Jacobson, Goldner and Maggio', 15);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (32, 'Cummings-Kulas', 18);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (33, 'Kessler, Rempel and Simonis', 15);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (34, 'Funk-Mayer', 15);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (35, 'Barrows-Mraz', 7);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (36, 'Raynor-Bosco', 10);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (37, 'Bogan LLC', 11);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (38, 'Smitham-Schamberger', 4);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (39, 'Auer and Sons', 18);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (40, 'Boyer-Stokes', 5);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (41, 'Witting-Schuppe', 14);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (42, 'Stracke Inc', 8);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (43, 'Balistreri, Goldner and Denesik', 19);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (44, 'West Group', 21);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (45, 'Kub and Sons', 5);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (46, 'Dooley-Ortiz', 7);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (47, 'Waters, Leannon and Nienow', 19);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (48, 'Grimes-Rath', 3);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (49, 'Zulauf-Lakin', 7);
INSERT INTO database_cloud_computing.tracks (track_id, track_name, artist_id) VALUES (50, 'Larkin-Hudson', 23);